import {
  CHAT_ERRORS,
  CHAT_FUNCTION_NAME,
  GEMINI_API_KEY_NAME,
  GEMINI_MODEL,
  GEMINI_REGION_BLOCKED_STATUS,
  GEMINI_RETRY_DELAY_MS,
  GEMINI_RETRY_STATUSES,
  GEMINI_TIMEOUT_MS,
  MISSING_API_KEY_MESSAGE,
} from "./chat";
import { GEMINI_SYSTEM_PROMPT } from "./gemini-prompt";

export const CHAT_FUNCTION_PATH = `supabase/functions/${CHAT_FUNCTION_NAME}/index.ts`;

/**
 * Source of the Supabase Edge Function that relays chat to Gemini. It is generated so the prompt
 * and messages stay in the app's TypeScript, while the function itself has no imports to resolve.
 * Every failure, including a malformed request, comes back as JSON `{ error }` with CORS headers,
 * so the browser can always read why a request failed.
 */
export function buildChatFunctionSource(): string {
  return `// @ts-nocheck
// Generated by src/lib/genogram/chat-function-source.ts. Edit that file and run \`npm run gen:chat-function\`.
const SYSTEM_PROMPT = ${JSON.stringify(GEMINI_SYSTEM_PROMPT)};
const GEMINI_MODEL = ${JSON.stringify(GEMINI_MODEL)};
const GEMINI_API_KEY_NAME = ${JSON.stringify(GEMINI_API_KEY_NAME)};
const MISSING_API_KEY_MESSAGE = ${JSON.stringify(MISSING_API_KEY_MESSAGE)};
const CHAT_ERRORS = ${JSON.stringify(CHAT_ERRORS)};
const GEMINI_TIMEOUT_MS = ${GEMINI_TIMEOUT_MS};
const GEMINI_RETRY_DELAY_MS = ${GEMINI_RETRY_DELAY_MS};
const GEMINI_RETRY_STATUSES = ${JSON.stringify(GEMINI_RETRY_STATUSES)};
const GEMINI_REGION_BLOCKED_STATUS = ${JSON.stringify(GEMINI_REGION_BLOCKED_STATUS)};
const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-region",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const JSON_HEADERS = { ...CORS_HEADERS, "Cache-Control": "no-store" };

function readApiKey() {
  const value = Deno.env.get(GEMINI_API_KEY_NAME);
  return typeof value === "string" ? value.trim() : "";
}

function jsonError(message, status) {
  return Response.json({ error: message }, { status, headers: JSON_HEADERS });
}

async function readChatRequest(request) {
  try {
    const body = await request.json();
    if (!body || typeof body.message !== "string" || typeof body.graph !== "object" || body.graph === null) return null;
    return { message: body.message, graph: body.graph };
  } catch {
    return null;
  }
}

function buildPrompt(graph, message) {
  return SYSTEM_PROMPT + "\\n\\n현재 가계도 JSON:\\n" + JSON.stringify(graph) + "\\n\\n사용자 요청:\\n" + message;
}

function readModelText(payload) {
  const text = payload?.candidates?.[0]?.content?.parts?.[0]?.text;
  return text?.trim() ? text : null;
}

function requestGemini(prompt, apiKey) {
  return fetch(
    "https://generativelanguage.googleapis.com/v1beta/models/" + GEMINI_MODEL + ":generateContent?key=" + encodeURIComponent(apiKey),
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      signal: AbortSignal.timeout(GEMINI_TIMEOUT_MS),
      body: JSON.stringify({
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        generationConfig: { responseMimeType: "application/json" },
      }),
    },
  );
}

async function rejectionMessage(response) {
  const payload = await response.json().catch(() => null);
  return payload?.error?.status === GEMINI_REGION_BLOCKED_STATUS ? CHAT_ERRORS.modelRegionBlocked : CHAT_ERRORS.modelFailed;
}

async function askGemini(prompt, apiKey) {
  try {
    let response = await requestGemini(prompt, apiKey);
    if (GEMINI_RETRY_STATUSES.includes(response.status)) {
      await new Promise((resolve) => setTimeout(resolve, GEMINI_RETRY_DELAY_MS));
      response = await requestGemini(prompt, apiKey);
    }
    if (GEMINI_RETRY_STATUSES.includes(response.status)) return { error: CHAT_ERRORS.modelBusy, status: 503 };
    if (!response.ok) return { error: await rejectionMessage(response), status: 502 };
    const text = readModelText(await response.json());
    return text ? { text } : { error: CHAT_ERRORS.emptyModelResponse, status: 502 };
  } catch (cause) {
    const timedOut = cause instanceof Error && cause.name === "TimeoutError";
    return timedOut ? { error: CHAT_ERRORS.modelTimeout, status: 504 } : { error: CHAT_ERRORS.modelFailed, status: 502 };
  }
}

async function handleChat(request, apiKey) {
  if (!apiKey) return jsonError(MISSING_API_KEY_MESSAGE, 500);
  const body = await readChatRequest(request);
  if (!body) return jsonError(CHAT_ERRORS.invalidRequest, 400);
  if (!body.message.trim()) return jsonError(CHAT_ERRORS.emptyMessage, 400);
  const result = await askGemini(buildPrompt(body.graph, body.message), apiKey);
  if ("error" in result) return jsonError(result.error, result.status);
  return Response.json({ reply: result.text }, { headers: JSON_HEADERS });
}

Deno.serve(async (request) => {
  if (request.method === "OPTIONS") return new Response("ok", { headers: CORS_HEADERS });
  try {
    return await handleChat(request, readApiKey());
  } catch {
    return jsonError(CHAT_ERRORS.unexpected, 500);
  }
});
`;
}
